<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>image_projection_plugin_interface</name>
  <version>0.0.0</version>
  <description>Base class for projection plugins</description>

  <maintainer email="oehler@sim.tu-darmstadt.de">Martin Oehler</maintainer>
  <author email="oehler@sim.tu-darmstadt.de">Martin Oehler</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>eigen</depend>
  <depend>hector_ros2_utils</depend>

  <export>
      <build_type>ament_cmake</build_type>
  </export>
</package>
