<?xml version='1.0' encoding='UTF-8'?>
<package format="2">
  <name>image_projection</name>
  <version>0.0.0</version>
  <description>image_projection is a ROS package to create various projections from multiple calibrated cameras.</description>
  <maintainer email="oehler@sim.tu-darmstadt.de">Martin Oehler</maintainer>
  <license>MIT</license>
  <!-- <url type="website">http://wiki.ros.org/image_projection</url> -->
  <author email="oehler@sim.tu-darmstadt.de">Martin Oehler</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>extended_camera_loader</depend>
  <depend>hector_ros2_utils</depend>
  <depend>image_projection_msgs</depend>
  <depend>image_projection_plugin_interface</depend>
  <depend>image_transport</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!--nodelet plugin="${prefix}/nodelet_plugins.xml" /-->
  </export>
</package>
